PREFIX=/etc

HOSTS = $(shell xargs -i find modules/{} -type f -name hosts < select | grep -v -f unselect)
GENSCRIPTS = $(shell xargs -i find modules/{} -type f -name genhosts < select | grep -v -f unselect)
GENHOSTS = $(patsubst %/genhosts,%/hosts,$(GENSCRIPTS))

HOSTS += $(GENHOSTS)

all: hosts

%/hosts: %/genhosts
	$< > $@

hosts: select unselect $(HOSTS)
	for i in $(HOSTS) ; do \
		printf "adding $$i\n"; \
		cat "$$i" >> tmp; \
	done
	printf "# the following redirections were generated by syg's hosts generator\n" > $@
	printf "# code available at: https://pedantic.software/git/~syg/hosts\n\n" >> $@
	printf "# this section is the custom header, you can modify it in header/hosts\n\n" >> $@
	cat header/hosts >> $@
	printf "\n# this section is a generated concatenation of tracking/malware websites, ads servers and time consooming websites\n\n" >> $@
	sed -n '/[ \t]localhost/d;s/^127\.0\.0\.1/0.0.0.0/;/^0.0.0.0 /p' < tmp | sort | uniq >> $@
	rm tmp

clean:
	rm -f hosts $(GENHOSTS)

install: hosts
	cp hosts $(PREFIX)
