PREFIX=/etc

EXTENSIONS = $(shell xargs -i find {} -type f -name hosts < select | grep -v -f unselect)
DYNEXT = $(shell xargs -i find {} -type d -empty < select | grep -v -f unselect)

EXTENSIONS += $(addsuffix /hosts,$(DYNEXT))

all: hosts

base/hosts: base/urls
	for u in $$(cat base/urls) ; do \
		printf "fetching $$u...\n"; \
		wget "$$u" -O - 2> /dev/null | tr -d '\015' >> base/hosts || echo "couldn't download from $$u"; \
		printf "\n\n" >> base/hosts; \
	done

extensions/google/search/hosts:
	# violent carpet ban of all international google search domains
	wget -O - https://www.google.com/supported_domains 2>/dev/null | sed 's/\.\(.*\)$$/0.0.0.0 \1\n0.0.0.0 www.\1/g' > $@

hosts: base/hosts select unselect $(EXTENSIONS)
	for i in $(EXTENSIONS) ; do \
		printf "adding $$i\n"; \
		cat "$$i" >> tmp; \
	done
	printf "# the following redirections were generated by syg's hosts generator\n" > $@
	printf "# code available at: https://pedantic.software/git/~syg/hosts\n\n" >> $@
	printf "# this section is the custom header, you can modify it in header/hosts\n\n" >> $@
	cat header/hosts >> $@
	printf "\n# this section is a generated concatenation of tracking/malware websites, ads servers and time consooming websites\n\n" >> $@
	sed -n '/[ \t]localhost/d;s/^127\.0\.0\.1/0.0.0.0/;/^0.0.0.0 /p' < tmp | sort | uniq >> $@
	rm tmp

clean:
	rm -f base/hosts hosts extensions/google/search/hosts

install: hosts
	cp hosts $(PREFIX)
